name: Build and Deploy MkDocs

on:
  push:
    branches:
      - docs  # Trigger on pushes to the docs branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Use the desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Build documentation
        run: mkdocs build  # Build the documentation

      - name: Checkout site branch
        run: |
          if git show-ref --verify --quiet refs/heads/site; then
              echo "برنچ site وجود دارد."
          else
              echo "برنچ site وجود ندارد. در حال ایجاد..."
              git checkout -b site  # Create and switch to the new branch
          fi
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Replace site contents
        run: |
          rm -rf *  # Remove existing files in the site branch
          echo "google-site-verification: googlee5febdfb3cd460f8.html" > googlee5febdfb3cd460f8.html 
          
          # Move new files from the build directory to the site branch only if they exist
          if [ -d ../site ]; then
              mv ../site/* ./  # Move new files from the build directory to the site branch
          else
              echo "Directory '../site' does not exist. No files to move."
          fi

      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Update documentation"  # Only commit if there are changes

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/ProdByGodfather/abarorm.git
          git push origin site  # Push changes to the site branch
