name: Build and Deploy MkDocs

on:
  push:
    branches:
      - docs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build documentation
        run: mkdocs build

      - name: Debug MkDocs Build
        run: |
          echo "Listing contents of '../site':"
          ls -la ../site

      - name: Ensure Site Directory
        run: mkdir -p ../site

      - name: Checkout site branch
        run: |
          if git show-ref --verify --quiet refs/heads/site; then
              git checkout site
          else
              git checkout -b site
          fi
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Replace site contents
        run: |
          # Safely remove files except .git and other essential files
          find . -mindepth 1 ! -name '.git' ! -name '.gitignore' -exec rm -rf {} +
          echo "google-site-verification: googlee5febdfb3cd460f8.html" > googlee5febdfb3cd460f8.html
          # Ensure site directory exists and copy its contents
          if [ -d ../site ]; then
              cp -r ../site/* ./
          else
              echo "Build directory '../site' does not exist or is empty."
          fi

      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "Update documentation"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push changes
        run: |
          git remote set-url origin git@github.com:ProdByGodfather/abarorm.git
          git push origin site --force
